os: linux
dist: bionic
language: shell

.opam: &OPAM
  language: shell
  services: docker
  install: |
    # Prepare the COQ container
    docker pull ${COQ_IMAGE}
    docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${PACKAGE} -w /home/coq/${PACKAGE} ${COQ_IMAGE}
    docker exec COQ /bin/bash --login -c "
      # This bash script is double-quoted to interpolate Travis CI env vars:
      echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
      set -ex  # -e = exit on failure; -x = trace for debug
      opam update -y
      opam pin add coq-hammer-tactics . -y -n -k path
      opam pin add coq-hammer . -y -n -k path
      opam install ${PACKAGE} -y -j ${NJOBS} --deps-only
      opam config list
      opam repo list
      opam list
      "
  script:
  - echo -e "${ANSI_YELLOW}Building ${PACKAGE}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
  - |
    docker exec COQ /bin/bash --login -c "
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
      set -ex
      sudo chown -R coq:coq /home/coq/${PACKAGE}
      opam install ${PACKAGE} -v -y -t -j ${NJOBS}
      "
  - docker stop COQ  # optional
  - echo -en 'travis_fold:end:script\\r'

jobs:
  include:

  # Test supported versions of Coq via OPAM
  - env:
    - COQ_IMAGE=coqorg/coq:8.16-ocaml-4.13-flambda
    - PACKAGE=coq-hammer.8.16.dev
    - NJOBS=2
    <<: *OPAM
  - env:
    - COQ_IMAGE=coqorg/coq:8.16-ocaml-4.13-flambda
    - PACKAGE=coq-hammer-tactics.8.16.dev
    - NJOBS=2
    <<: *OPAM
